### ISSUE TITLE
Documentation refers to incorrect secret

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/roundup-action#7]
## 🐛 Describe the bug
The `README.md` lists an example workflow `.yaml` file with the following:

```yaml
env:
    ADMIN_GITHUB_TOKEN: ${{secrets.pat}}
    CODE_SIGNING_KEY:   ${{secrets.CODE_SIGNING_KEY}}
    ossrh_username:     jocowboy
    ossrh_password:     ${{secrets.OSSRH_USERNAME}}
    pypi_username:      snakewrangler
    pypi_password:      ${{secrets.PYPI_PASSWORD}}
```

However, the `ossrh_password`'s value refers to an `OSSRH_USERNAME` secret. It should be an `OSSRH_PASSWORD` secret.

## 📑 To Reproduce

1. Go to https://github.com/NASA-PDS/roundup-action
2. Scroll down to the GitHub-rendered README.
3. Scroll further down to "Demonstration" section
4. See the incorrect `ossrh_password` demonstration value.

## 🧐 Expected behavior
The entry should read:
```yaml
ossrh_password: ${{secrets.OSSRH_PASSWORD}}
```

## 🧩 Version of Software Used

Output from `validate -V`:
```console
validate: Command not found.
```

## 🩺 Test Data / Additional context

There is no test data nor any additional context.

## 🖥 Desktop (please complete the following information)

 - OS: macOS 10.15.7
 - Browser: Safari 14.0 (15610.1.28.1.9, 155610)
 - Version: `master`

## 🦄 Applicable requirements

None applicable.

## 🖼 Screenshots

![Screen Shot 2020-11-05 at 3 51 24 PM](https://user-images.githubusercontent.com/814813/98300453-eb5ccd00-1f7e-11eb-90d5-abd0a6e9bf1e.png)
